app:
  base-url: http://localhost:${server.port:8080}
spring:
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: OFF
  resources.cache.cachecontrol.max-age: 86400 # 1d
  servlet.multipart:
    max-file-size: 2MB
    max-request-size: 3MB
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  output.ansi.enabled: ALWAYS
  security:
    user:
      name: admin
      password: admin

